define names = ['Ibrahim', 'Mikołaj', 'Wesa', 'Phanom', 'Meili', 'Saki',
         'Shirin', 'Elif', 'Neha', 'Pallavi', 'Mauro', 'Renato', 'Alexandra',
         'Patryk', 'Arzu', 'Li', 'Nina', 'Nicola', 'Waya', 'Martyna',
         'Chalerm', 'Haruto', 'Magdalena', 'Derya', 'Pornthip', 'Kai', 'Asha',
         'Marlene', 'Jannis', 'Kihyun', 'Zdenek', 'Andres', 'Seokjin', 'Diego',
         'Ahmet', 'Ellen', 'Teodora', 'Vladimir', 'Timur', 'Matilda', 'Eirini',
         'Petros', 'Meifen', 'Violeta', 'Petar', 'Riccardo', 'Apinya',
         'Somporn', 'Randa', 'Felix', 'Kosei', 'Clara', 'Hiwot', 'Ida',
         'Lucas', 'Alexei', 'Aspasia', 'Angeliki', 'Francesca', 'Khanh',
         'Tamara', 'Tallulah', 'Eunji', 'Emmi', 'Thiago', 'Nora', 'Paweł',
         'Thao', 'Mongkol', 'Cansu', 'Halyna', 'Daniela', 'Hermanni', 'Asude',
         'Tilda', 'Xiaojing', 'Sawasdee', 'Karel', 'Bungorn', 'Wahanassatta',
         'Eray', 'Busra', 'Baris', 'Mia', 'Rajesh', 'Sophia', 'Ximena',
         'Sunil', 'Asli', 'Hana', 'Sebastian', 'Hilda', 'Ilmari', 'Daniel',
         'Fikir', 'Rajiv', 'Tian', 'Ezgi', 'Jiayi', 'Matias', 'Jesper',
         'Fabio', 'Stefan', 'Arisa', 'Veronika', 'Chalad', 'Tariq', 'Kidan',
         'Olga', 'Saksit', 'Mulu', 'Mekonnen', 'Melina', 'Shilah', 'Dimitris',
         'Jakob', 'Salvatore', 'Mio', 'Semyon', 'Valentina', 'Bartłomiej',
         'Prapaporn', 'Aleksi', 'Alemayehu', 'Giannis', 'Rajendra', 'Xiaohong',
         'Niran', 'Ossi', 'Yorgos', 'Tung', 'Yuriko', 'Janne', 'Airi', 'Timo',
         'Sangho', 'Sławomir', 'Roberta', 'Lea', 'Hulya', 'Chonlada',
         'Kanthika', 'Wondimu', 'Wondwosen', 'Robin', 'Dawit', 'Selam',
         'Pradeep', 'Eleonora', 'Raphael', 'Ihor', 'Pinar', 'Nadiya', 'Andrei',
         'Yun', 'Songpol', 'Lena', 'Gagik', 'Branislav', 'Daria', 'Aleksandar',
         'Laila', 'Tamer', 'Giuseppe', 'Oscar', 'Francesco', 'Valeriya',
         'Samira', 'Naveen', 'Hamza', 'Nozomi', 'Odina', 'Merve', 'Iina',
         'Anatoly', 'Sinan', 'Anjali', 'Lucine', 'Hasmik', 'Julia', 'Mai',
         'Kaito', 'Taras', 'Maximilian', 'Otto', 'Shan', 'Ramesh', 'Ling',
         'Oliver', 'Hovhannes', 'Nikos', 'Sami', 'Asuman', 'Klara', 'Yu',
         'Xiaoming', 'Luka', 'Karen', 'Yodit', 'Teresa', 'Somchai', 'Piotr',
         'Liana', 'Gebre', 'Roman', 'Yuki', 'Charlotte', 'Valeria', 'Yeliz',
         'Vera', 'Ratanaporn', 'Tobias', 'Meklit', 'Erdogan', 'Yelena',
         'Wiktoria', 'Sosuke', 'Nikolay', 'Sarika', 'Bruk', 'Alma', 'Ali',
         'Layla', 'Kateryna', 'Kaya', 'Kitchi', 'Monica', 'Cheng', 'Viljami',
         'Ryoma', 'Levin', 'Desta', 'Bashar', 'Walid', 'Kazuma', 'Sangeeta',
         'Umit', 'Klaudia', 'Johan', 'Emre', 'Madhu', 'Thanchanok', 'Youssef',
         'Ai', 'Maciej', 'Nonglak', 'Hedda', 'Hai', 'Minh', 'Kalle', 'Paolo',
         'Tatevik', 'Nemanja', 'Stefano', 'Juha', 'My', 'Elżbieta', 'Xiaoyun',
         'Ahmed', 'Ebru', 'Vahan', 'Xiaoyan', 'Lina', 'Hakan', 'Kriangkrai',
         'Okan', 'Artem', 'Alok', 'Saowalak', 'Luigi', 'Anders', 'Ashish',
         'Seojoon', 'Emily', 'Serhiy', 'Sirima', 'Genet', 'Tatiana', 'Nils',
         'Pankaj', 'Somphote', 'Eleni', 'Sanjay', 'Jussi', 'Fatima',
         'Tawatchai', 'Pranee', 'Silvia', 'Luna', 'Daranee', 'Yupaporn',
         'Savita', 'Mazen', 'Jana', 'Santeri', 'Moritz', 'Mesfin', 'Kohana',
         'Iida', 'Signe', 'Yana', 'Osman', 'Venla', 'Dmytro', 'Daiki', 'Liwei',
         'Tuan', 'Benjamin', 'Lucia', 'Kento', 'Sasithorn', 'Thongmit', 'Sara',
         'Rachna', 'Huy', 'Lars', 'Lucie', 'Ayaka', 'Selin', 'Sunita',
         'Ohanzee', 'Grace', 'Kostas', 'Andriy', 'Leyla', 'Levon', 'Kannikar',
         'Ting', 'Hatice', 'Leszek', 'Leila', 'Rita', 'Nikolai', 'Giovanni',
         'Wiwat', 'Adam', 'Onur', 'Rima', 'Betelhem', 'Narumon', 'Imad',
         'Rasmus', 'Somnuk', 'Shohei', 'Astrid', 'Avery', 'Meron', 'Michele',
         'Matthew', 'Rabia', 'Liam', 'Aleksei', 'Suresh', 'Andrzej', 'Deepa',
         'Patchara', 'Mikhail', 'Mayumi', 'Tarek', 'Ryo', 'Lilja', 'Tazanna',
         'Gustaf', 'Johannes', 'Ammar', 'Linnea', 'Eva', 'Liang', 'Fahad',
         'Dina', 'Emelie', 'Jihan', 'Suthida', 'Burak', 'Somboon', 'Orest',
         'Marija', 'Sofie', 'Naoki', 'Serkan', 'Amanda', 'Victor', 'Sultan',
         'Stella', 'Jiyeon', 'Juuso', 'Ugur', 'Hala', 'Joonas', 'Emir',
         'Tereza', 'Ming', 'Dominika', 'Aiden', 'Anna', 'Antonella', 'Zerihun',
         'Leni', 'Nopparat', 'Vinh', 'Elijah', 'Dariusz', 'Sarah', 'Aria',
         'Lilit', 'Elias', 'Zewdu', 'Logan', 'Vikram', 'Taiga', 'Rania',
         'Rakesh', 'Jia', 'Aarne', 'Ryosuke', 'Giorgio', 'Raffaella', 'Ingrid',
         'Yohannes', 'Mohammed', 'Pavlos', 'Haruka', 'Kazuki', 'Nadezhda',
         'Lova', 'Chayathon', 'Vijay', 'Endalkachew', 'Ceren', 'Noora',
         'Irene', 'Noah', 'Wael', 'Lara', 'Nikita', 'Barbara', 'Stefania',
         'Nga', 'Marko', 'Mert', 'Rahma', 'Orhan', 'Léa', 'Vivek', 'Sulaiman',
         'Khalil', 'Shota', 'Shu', 'George', 'Wayan', 'Malak', 'Priya',
         'Sornchai', 'Samuel', 'Chayton', 'Raed', 'Elan', 'Vincent', 'Vadim',
         'Ziad', 'Sofija', 'Yong', 'Tirunesh', 'Fadi', 'Dalal', 'Michela',
         'Evelyn', 'Danae', 'Marco', 'Aada', 'Thana', 'Ekaterina', 'Hoda',
         'Domenico', 'Geeta', 'Tsubasa', 'Rina', 'Oliwia', 'Kanchan', 'Maya',
         'Amani', 'Nhat', 'Noura', 'Lamia', 'Kiran', 'Oleksandr', 'Dilek',
         'Maksim', 'Bartosz', 'Andrea', 'Gennady', 'Petr', 'Ksenia',
         'Leonardo', 'Lenka', 'Julius', 'Eemeli', 'Josef', 'Nikolina', 'Vinod',
         'Hung', 'Amnart', 'Aram', 'Svea', 'Ladda', 'Tomáš', 'Adel', 'Kohei',
         'Bilen', 'Tai', 'Katerina', 'Pramote', 'Rola', 'Eylem', 'Houda',
         'Filip', 'Saba', 'Angela', 'Marie', 'Somsak', 'Aiko', 'Sonali',
         'Mira', 'Tetiana', 'Lauri', 'Giovanna', 'Pekka', 'Nicolas', 'Kinga',
         'Alem', 'Yachne', 'Lily', 'Naji', 'Rui', 'Zehra', 'Karol', 'Harper',
         'Tizita', 'Marta', 'Sandeep', 'Majid', 'Mika', 'Sooyoung', 'Sho',
         'Siiri', 'Lovisa', 'Nadia', 'William', 'Aleksandra', 'Dereje',
         'Jinwoo', 'Nabil', 'Minji', 'Ashot', 'Mona', 'Tomas', 'Huong',
         'Serena', 'Hoa', 'Berhanu', 'Khaled', 'Nasser', 'Niko', 'Aisha',
         'Mana', 'Caroline', 'Wen', 'Halona', 'Jitka', 'Mounir', 'Duc',
         'Tuyet', 'Lan', 'Yue', 'Ferdi', 'Samuli', 'Libuše', 'Wilaiwan',
         'Wilma', 'Aiyana', 'Sita', 'Jaroslav', 'Orapan', 'Can', 'Tabea',
         'Nada', 'Sukhon', 'Helmiina', 'Lukas', 'Michalis', 'Dinesh', 'Meera',
         'Ogin', 'Antonio', 'Natalia', 'Meral', 'Haile', 'Tadeusz', 'Ayiana',
         'Tuncay', 'Gul', 'Milica', 'Andjela', 'Bojan', 'Takeshi', 'Ester',
         'Hayle', 'Aukusti', 'Bjorn', 'Kyungsoo', 'Ferhat', 'Asami', 'Mateusz',
         'Prashant', 'Wanida', 'Oskari', 'Fredrik', 'Assefa', 'Zhen', 'Kacper',
         'Catalina', 'Mariana', 'Jose', 'Satsuki', 'Radek', 'Eliška', 'Faisal',
         'Pooja', 'Sirichai', 'Phuong', 'Miroslav', 'Biruktawit', 'Boris',
         'Lamis', 'Fatma', 'Antonis', 'Elena', 'Phichit', 'Chrysa', 'Paul',
         'Erdem', 'Sergio', 'Katharina', 'Carlo', 'Yordanos', 'Thongchai',
         'Tayen', 'Salma', 'Maija', 'Tiva', 'Esra', 'Hikari', 'Freja',
         'Georgia', 'Zeynep', 'Amira', 'Sora', 'Jisoo', 'Simone', 'Takumi',
         'Inola', 'Chaisit', 'Kavita', 'Krzysztof', 'Rikuto', 'Huan', 'Pavla',
         'Hanan', 'Rasha', 'Ela', 'Aoi', 'Svetlana', 'Luis', 'Christos',
         'Lusine', 'Vasyl', 'Leon', 'Aino', 'Shilpa', 'Alessio', 'Axel',
         'Artur', 'Anton', 'Szymon', 'Alexander', 'Joanna', 'Victoria',
         'Tigist', 'Hani', 'Yeonwoo', 'Linh', 'Anatoliy', 'Bojana', 'Kibrom',
         'Ranjana', 'Apichat', 'Nikola', 'Hanna', 'Hilla', 'Rika', 'Magnus',
         'Tolga', 'Elizabeth', 'Mateo', 'Raisa', 'Frantisek', 'Dorota',
         'Abera', 'Alla', 'Yuto', 'Aida', 'Roula', 'Phakpoom', 'Roza', 'Kemal',
         'Artturi', 'Serdar', 'Ebba', 'Saron', 'Armen', 'Mason', 'Said',
         'Agnes', 'Pimchanok', 'Farah', 'Yoki', 'Jing', 'Dat', 'Ege', 'Borys',
         'Carine', 'Ying', 'Zuzanna', 'Damian', 'Chanakan', 'Suman',
         'Cristina', 'Renata', 'Nur', 'Sauli', 'Levent', 'Sarkis', 'Amelie',
         'Trang', 'Ayumi', 'Yulia', 'Pichet', 'Marcello', 'Jovana', 'Tyra',
         'Nicolo', 'Inna', 'Marek', 'Arev', 'Paola', 'Emanuele', 'Thanyarat',
         'Wei', 'Mamdouh', 'Aysun', 'Kornelia', 'Amina', 'Inkeri', 'Kaori',
         'Ayita', 'Artyom', 'Elisabetta', 'Kiona', 'Xin', 'Elsa', 'Ratchasak',
         'Zewde', 'Maka', 'Rami', 'Emanuel', 'Quoc', 'Mykhailo', 'Prasert',
         'Arjun', 'Halian', 'Ismail', 'Mina', 'Kenji', 'Lyudmila', 'Leah',
         'Mila', 'Thidarat', 'Luisa', 'Soyeon', 'Nisara', 'Nisha', 'Vrezh',
         'Yonas', 'Qing', 'Kamil', 'Ravi', 'Volodymyr', 'Sosina', 'Shunya',
         'Ana', 'Giulia', 'Fedor', 'Hasan', 'Pietro', 'Xiaojun', 'Karim',
         'Asrat', 'Irina', 'Joumana', 'Philipp', 'Carlos', 'Santiago', 'Amr',
         'Wojciech', 'Suleyman', 'Karl', 'Jian', 'Julian', 'Layan', 'Abigail',
         'Maurizio', 'Lien', 'David', 'Dusan', 'Yuwadee', 'Xiaoxi', 'Yuriy',
         'Kadir', 'Enapay', 'Praphasorn', 'Fernanda', 'Sima', 'Dominik',
         'Adnan', 'Federica', 'Jonas', 'Chaska', 'Ava', 'Takuma', 'Kokoro',
         'Ilari', 'Zuni', 'Anahit', 'Rachaneekorn', 'Margarita', 'Alemnesh',
         'Martin', 'Joakim', 'Rani', 'Alena', 'Patrycja', 'Vyacheslav',
         'Larisa', 'Reina', 'Recep', 'Haeun', 'Patrizia', 'Eero', 'Dima',
         'Amit', 'Dmitry', 'Jiri', 'Fabian', 'Kamal', 'Chun', 'Tsige', 'Irini',
         'Yara', 'Alyona', 'Nea', 'Poonam', 'Hania', 'Tetsuya', 'Claudio',
         'Topi', 'Mei', 'Oleksiy', 'Elli', 'Xiaowei', 'Nadine', 'Suren',
         'Helmi', 'Gopal', 'Saori', 'Alessandro', 'Stanisław', 'Dragan',
         'Duygu', 'Johanna', 'Stelios', 'Meryem', 'Katarzyna', 'Narine',
         'Neetu', 'Carl', 'Etenesh', 'Xiaofang', 'Tsehay', 'Girma', 'Taemin',
         'Tsion', 'Yiska', 'Yuma', 'Iryna', 'Yakone', 'Gevorg', 'Rahel',
         'Elin', 'Finn', 'Charbel', 'Preecha', 'Manju', 'Yakota', 'Sevda',
         'Oskar', 'Enrico', 'Laura', 'Tadesse', 'Karolina', 'Sona', 'Hande',
         'Khalid', 'Juan', 'Luca', 'Somkid', 'Olivia', 'Alemu', 'Yusuke',
         'Mizuki', 'Jelena', 'James', 'Ondrej', 'Samar', 'Takuya', 'Garo',
         'Vlastimil', 'Kumari', 'Ivana', 'Larysa', 'Nana', 'Dimitra', 'Mariya',
         'Aneta', 'Annalisa', 'Massimo', 'Saranya', 'Xuan', 'Yoshiko',
         'Elvira', 'Melis', 'Almaz', 'Nakoma', 'Yuta', 'Serhat', 'Georgios',
         'Yousef', 'Ryota', 'Mikko', 'Maja', 'Enola', 'Hina', 'Agnieszka',
         'Naglaa', 'Joseph', 'Pinja', 'Riley', 'Yasemin', 'Roberto', 'Michal',
         'Lasse', 'Mustafa', 'Rupa', 'Edyta', 'Lama', 'Hua', 'Vojislav',
         'Zewditu', 'Tekle', 'Farid', 'Svitlana', 'Manoj', 'Yona', 'Aapeli',
         'Cinzia', 'Ewa', 'Marcin', 'Rosa', 'Amar', 'Saara', 'Adrian', 'Rafał',
         'Roosa', 'Ratchadaporn', 'Kana', 'Najwa', 'Duangrat', 'Ani', 'Hoseok',
         'Thu', 'Irena', 'Sezen', 'Tigran', 'Grzegorz', 'Asem', 'Alina',
         'Hyejin', 'Henry', 'Jakub', 'Aya', 'Sotiris', 'Iiris', 'Jiho', 'Lari',
         'Oleg', 'Minho', 'Onni', 'Sandro', 'Lulit', 'Chatchai', 'Paraskevi',
         'Hao', 'Kristina', 'Orasa', 'Jun', 'Harish', 'Marketa', 'Alexandros',
         'Olena', 'Haruki', 'Kyoko', 'Małgorzata', 'Gustav', 'Iris',
         'Elizaveta', 'Riku', 'Ismo', 'Meng', 'Gianfranco', 'Yusuf', 'Dawid',
         'Petro', 'Abebe', 'Xiaohui', 'Fang', 'Lorenzo', 'Mara', 'Ayse',
         'Deniz', 'Yasin', 'Ella', 'Hinata', 'Taeyang', 'Riko', 'Lenny',
         'Tuomas', 'Weronika', 'Gizem', 'Zofia', 'Anand', 'Giuseppina',
         'Rabih', 'Swati', 'Nihan', 'Ivan', 'Peter', 'Tomasz', 'Jonathan',
         'Alicja', 'Seble', 'Alessandra', 'Selamawit', 'Emmy', 'Solomon',
         'Sungmin', 'Pelin', 'Thanes', 'Emine', 'Apostolos', 'Vangelis', 'Jan',
         'Sofia', 'Leevi', 'Abdullah', 'Gabriela', 'Vardan', 'Ermias', 'Elmas',
         'Michael', 'Amelia', 'Eetu', 'Michel', 'Costas', 'Dalia', 'Nuray',
         'Vasiliki', 'Erik', 'Sergei', 'Xiu', 'Tim', 'Pasquale', 'Mikael',
         'Camila', 'Fasika', 'Akiko', 'Nikoleta', 'Nelly', 'Huseyin',
         'Chompoonut', 'Vuk', 'Mykola', 'Arif', 'Hassan', 'Joel', 'Monika',
         'Gabriel', 'Yasmin', 'Yuri', 'Martina', 'Hanh', 'Sakura', 'Yuji',
         'Despina', 'Zahra', 'Xia', 'Eri', 'Mario', 'Tala', 'Lotta', 'Yui',
         'Fabiola', 'Emilia', 'Salali', 'Liubov', 'Michał', 'Hannah', 'Jamal',
         'Maiyun', 'Inka', 'Giacomo', 'Isabella', 'Zoya', 'Nenad', 'Tatyana',
         'Galina', 'Dana', 'Pongchai', 'Zufan', 'Joonho', 'Konstantin',
         'Naree', 'Nirut', 'Alberto', 'Simon', 'Chawalit', 'Samir', 'Henrik',
         'Ethan', 'Makar', 'Pavel', 'Mintwab', 'Federico', 'Chartchai',
         'Talulah', 'Eeva', 'Marina', 'Zhixiang', 'Takashi', 'Gonca', 'Sophie',
         'Suzu', 'Katarina', 'Cem', 'Catori', 'Marcelina', 'Milan', 'Agata',
         'Nakota', 'Mireille', 'Keita', 'Sukanya', 'Djordje', 'Arman', 'Yi',
         'Łukasz', 'Milos', 'Omar', 'Mehmet', 'Nour', 'Sarita', 'Scarlett',
         'Chloe', 'Sini', 'Rahul', 'Igor', 'Angelo', 'Ajay', 'Hussein',
         'Jyoti', 'Hui', 'Yasah', 'Davide', 'Sanni', 'Emi', 'Aava', 'Vaclav',
         'Thuy', 'Niklas', 'Yan', 'Emma', 'Anh', 'Chaiyaporn', 'Subhash',
         'Eunbi', 'Saku', 'Andreas', 'Panagiotis', 'Kirill', 'Olha', 'Raja',
         'Caterina', 'Daniil', 'Justyna', 'Yuna', 'Oksana', 'Zuzana',
         'Mengistu', 'Ilayda', 'Juhani', 'Arttu', 'Anita', 'Tomi', 'Gokhan',
         'Zhi', 'Mari', 'Paula', 'Linus', 'Tijana', 'Boonchit', 'Alice',
         'Misaki', 'Sibel', 'Cengiz', 'Spiros', 'Satine', 'Luciana', 'Tony',
         'Moe', 'Avinash', 'Isak', 'Denis', 'Pattraporn', 'Tom', 'Bao',
         'Apsorn', 'Hiroshi', 'Viktor', 'Gianluca', 'Radosław', 'Yavuz',
         'Sinchai', 'Raffaele', 'Maria', 'Simona', 'Thanos', 'Xiaoli',
         'Yiannis', 'Gianna', 'Nesrin', 'Phongchai', 'Amanuel', 'Paulina',
         'Kasperi', 'Ufuk', 'Kota', 'Winona', 'Arun', 'Takoda', 'Vincenzo',
         'Eren']

# A lot of names in this random list are too long to look good with current UI
define short_names = [name for name in names if len(name) < 8]
